use super::WeaponClass;

#[derive(Clone, Copy, Debug)]
pub struct WeaponStats {
    pub class: WeaponClass,
    pub name: &'static str,
    pub visibility_range: f32,
    pub visibility_half_angle_deg: f32,
    pub aim_cone_render_range: f32,
    pub aim_base_half_angle_deg: f32,
    pub movement_spread_max_deg: f32,
    pub bullet_speed: f32,
    pub bullet_damage: u32,
    pub recoil_per_shot_deg: f32,
    pub recoil_max_deg: f32,
    pub recoil_decay_deg_per_sec: f32,
    pub fire_rate_rps: f32,
    pub mag_size: u32,
    pub reload_time_secs: f32,
    pub ads_time_secs: f32,
    pub weapon_swap_time_secs: f32,
    pub sprint_to_fire_time_secs: f32,
    pub hip_fire_spread_deg: f32,
    pub damage_falloff_range: f32,
    pub penetration_power: f32,
    pub shot_sound_radius: f32,
    pub minimap_signature: f32,
    pub muzzle_flash_intensity: f32,
    pub ads_move_speed_mult: f32,
    pub strafe_spread_penalty_mult: f32,
    pub jump_stability_mult: f32,
    pub ping_visibility_mult: f32,
    pub detection_strength_mult: f32,
    pub enemy_mark_duration_mult: f32,
}
